### ISSUE TITLE
跑demo时候我切换到项目的gift/demoRes下运行了gift_install.sh

### ISSUE THREAD

**Issue by neimengwuyanzu** [bytedance/AlphaPlayer#19]
提示崩溃

`2020-11-10 10:24:06.425 22610-22610/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ss.ugc.android.alphavideoplayer, PID: 22610
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:7201)
        at android.view.View.performClickInternal(View.java:7170)
        at android.view.View.access$3500(View.java:806)
        at android.view.View$PerformClick.run(View.java:27562)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:7201) 
        at android.view.View.performClickInternal(View.java:7170) 
        at android.view.View.access$3500(View.java:806) 
        at android.view.View$PerformClick.run(View.java:27562) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7697) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ss.ugc.android.alphavideoplayer.model.ConfigModel$Item com.ss.ugc.android.alphavideoplayer.model.ConfigModel.getPortraitItem()' on a null object reference
        at com.ss.ugc.android.alphavideoplayer.VideoGiftView.startVideoGift(VideoGiftView.kt:65)
        at com.ss.ugc.android.alphavideoplayer.MainActivity.playGift(MainActivity.kt:75)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:7201) 
        at android.view.View.performClickInternal(View.java:7170) 
        at android.view.View.access$3500(View.java:806) 
        at android.view.View$PerformClick.run(View.java:27562) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7697) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) `

是我运行的方式不对么

手机是一加5t 系统是Android10

**Comment by DymanZy** [comment]
看起来推测是你导入的资源的config.json文件有问题，只是个简单的NPE错误，调试一下相信你可以找到具体原因的 ：）

**Comment by axiangpro** [comment]
我也遇到同样的问题，请问是怎么解决的

**Comment by lsgfly** [comment]
> 我也遇到同样的问题，请问是怎么解决的

./android/gift_install.sh android/gift/demoRes
