### ISSUE TITLE
使用GLTextureView播放频繁mp4礼物半小时闪退

### ISSUE THREAD

**Issue by iStride17** [bytedance/AlphaPlayer#51]
报错位置如下：

java.lang.RuntimeException: createContext failed: 12291
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$i.k(GLTextureView.java:2)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$i.j(GLTextureView.java:1)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$i.h(GLTextureView.java:12)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$j.d(GLTextureView.java:45)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$j.run(GLTextureView.java:2)

java.lang.RuntimeException: createContext failed: 12291
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$i.k(GLTextureView.java:2)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$i.j(GLTextureView.java:1)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$i.h(GLTextureView.java:12)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$j.d(GLTextureView.java:45)
	at com.ss.ugc.android.alpha_player.widget.GLTextureView$j.run(GLTextureView.java:2)

**Comment by iStride17** [comment]
版本1.2.0 Android
